name: Build Release
on:
  release:
    types:
      - created
jobs:
  create-release:
    runs-on: 'ubuntu-20.04'
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create-release
      uses: ncipollo/release-action@v1
      with:
        omitBody: true
        prerelease: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ${{ matrix.os }}
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        platform:
          - 'linux-x64'
    
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Build server
        run: |
          make server
      
      - name: Upload server
        uses: actions/upload-artifact@v1
        with:
          name: whisper-server
          path: server

  upload-release-assets:
    runs-on: 'ubuntu-20.04'
    needs: [create-release, build] 
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: whisper-server
          path: downloaded-server

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: downloaded-server/server
          asset_name: whisper-server
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}